# Generated by Django 5.2.4 on 2025-09-07 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grua_app', '0013_configuracionempresa_estadisticadiaria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfiguracionEmpresa',
        ),
        migrations.DeleteModel(
            name='EstadisticaDiaria',
        ),
        migrations.DeleteModel(
            name='ReporteMensual',
        ),
        migrations.AlterField(
            model_name='codigoverificacion',
            name='tipo',
            field=models.CharField(choices=[('reset_password', 'Reset Password'), ('verificacion_email', 'Email Verification')], max_length=25),
        ),
        migrations.AlterField(
            model_name='notificacionadmin',
            name='tipo',
            field=models.CharField(choices=[('nueva_solicitud', 'Nueva Solicitud'), ('pago_confirmado', 'Pago Confirmado'), ('servicio_completado', 'Servicio Completado')], max_length=25),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='numero_orden',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitudservicio',
            name='placa_vehiculo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('grua_liviana', 'Grúa Liviana'), ('grua_pesada', 'Grúa Pesada'), ('auxilio_mecanico', 'Auxilio Mecánico')], max_length=25),
        ),
    ]
